### ISSUE TITLE
Missing data for trade details

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#16] opened 2024-01-02 15:05 UTC
When I am connected to the TWS, the individual prices of the single legs are missing as shown on your picture in the readme. Each line has its own P/L, which I would like to see. I am also interested in the current option price. Maybe you can display it in a column.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/891f2190-8f78-408f-b327-5b56484190f6)

**Comment by PaulSquires** [comment] 2024-01-02 19:13
There was a reason I removed it in this new version..... I just can't remember 100% why at the moment. I think it was related to the leg market price being correct but if the leg had been rolled previously then the leg cost basis was wrong. I will check into this again and put it back if it works without causing confusion for the user.

**Comment by Flippo24** [comment] 2024-01-02 21:43
At this point you can view the calculation of the positions again. The amount on a leg is already the amount of the entire position. The individual position value is incorrect here.
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/34e0ca62-ebaa-4b2c-a596-2de408ebadf0)

**Comment by PaulSquires** [comment] 2024-01-05 15:27
I am taking another look at this issue and will add back the leg cost, market value, difference, and percentage. Much like the older IB-Tracker functionality. Once I implement the changes then we should discuss it again to be sure that it meets our needs. I am hoping to have this change done today.

**Comment by PaulSquires** [comment] 2024-01-05 17:03
Just finished adding the new functionality. Source code updated in repository. Looks pretty good. Here is a screenshot:

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/b6a85b05-d028-40b5-944e-8a5017469f1c)

**Comment by Flippo24** [comment] 2024-01-05 18:55
It looks good visually, but please check the calculation again. How can the values in both rows be the same in this case? Please describe how the values are calculated. 
I assume that the red values on the right should signal a loss. Actually, it is still in profit.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/62c3d520-70fe-41c4-baa5-cbac9919ba93)

**Comment by PaulSquires** [comment] 2024-01-05 19:22
![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/4a0d8674-7bdd-47a7-a7b8-5e3ac9410f59)

For the option legs:
- First column is the average cost of the leg (as calculated and retried from TWS). I don't know how IBKR calculates this amount because this is the reason that I had originally dropped it from the new TradeTracker. 
- Second column. The current market value of the option and how much you would have to pay to close them.
- Third column. A simple difference between the first two columns.
- Fourth column. Percentage for value left in the leg. Even though the first column can vary, knowing the percentage of value left in the leg is a good approximation for deciding whether to close the leg (say, if your 50% profit goal has been reached).
I am not sure why in the first column one of your legs is green and the other is red. That is a display bug. Both should be a neutral gray color. I'll fix that.

**Comment by PaulSquires** [comment] 2024-01-05 19:26
> Actually, it is still in profit.

Looks like the current market value of your Put legs would cost you $2851.02 each to close (total $5702.04). Your current income received on the trade is $3721.30, so it appears you are not currently profitable for this trade(?)

**Comment by Flippo24** [comment] 2024-01-05 19:29
Last close is 7.00$
4 * 100 *7 = 2800.
so I need 2800 to close the whole position. Not just one leg.

**Comment by PaulSquires** [comment] 2024-01-05 19:40
Ah, okay, I see what the problem is now. Both option legs are exactly the same.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/475d1c31-720e-4d0e-bf04-065df14fa006)

The data retrieved from TWS is getting the full 4 positions whereas in TradeTracker you have them split into two different transactions and when I loop the grid, I (incorrectly) display the TWS 4 contract value for both of your legs.

I need to fix it so that duplicate option legs are combined into one.

**Comment by Flippo24** [comment] 2024-01-05 19:44
Please use the values entered in the transaction as the starting point. Please do not divide the value of the TWS by the number of legs.

**Comment by PaulSquires** [comment] 2024-01-05 19:46
I will combine both of the legs so that it shows in the grid as -4 Feb 16 42d 65 P. That way it will match what shows in TWS and also match the value that TWS sends to TradeTracker.

**Comment by Flippo24** [comment] 2024-01-05 19:48
No, please don't do that. Because you can look at both positions separately. Each has its own PnL.

**Comment by Flippo24** [comment] 2024-01-05 19:55
Take the value from the transaction for the first column. In my opinion, it is not necessary to take the value from the TWS.
If you were to combine it, then the same would appear in the line as in the line with the underlying. It would make even less sense to see the same thing twice.

**Comment by PaulSquires** [comment] 2024-01-05 20:07
Maybe I am not understanding correctly. Maybe more talk about this may help.

The first column is calculated from incoming TWS data:
position_cost = (pd.average_cost * ld->leg->open_quantity);   // pd.average comes from TWS and is cost per 1 PUT

Instead of using that data, I could use the two values that show in the Trade History for your legs (the values that you had manually entered:  1920.70 and 1800.60). I like that idea.

It is the second column that I was mostly referring to previously. That amount is not calculated by me, and is simply the amount that comes in from TWS. The problem is that the amount is the total of all 4 of your Puts and not just 2. To be correct, I would have to take the 2851.02, divide it by 2, and display 1425.51 for each leg in column #2.

Does that sound right?

**Comment by Flippo24** [comment] 2024-01-05 20:22
For column one:
The value of the transaction history is completely ok.
The background is this:
Sell 1 put for 10$ premium if you want to buy it back for 50% it would be 5$.
If you sell the same put again during the term, say for 6$ and want to buy it back at 50%, that would be 3$. So both separately.
If you combine them now, 50% would be $4.

For the second column:
Just calculate it yourself. 
I prefer to use the TWS model price in my spreadsheet. You certainly won't get it.
You could calculate the last close * position. You also have the multiplier in the transaction.
If you want to make it even more precise, then take the ask price for puts/calls sold and the bid price for puts/calls bought. This would have the advantage that a price is available even if there is little trading activity.

**Comment by PaulSquires** [comment] 2024-01-08 02:14
Added new code to calculate the cost basis of individual Option legs. Needs to be tested on new data because the calculation can not be applied to transactions created before this patch. I will see how well this code works this week in a live setting when connected to TWS. Actually, older existing Trades may display correct data UNLESS they contain rolled transactions. In that case, the calculation will be incorrect.

**Comment by Flippo24** [comment] 2024-01-08 11:28
The value for column 1 is now correct. Great so far.
But I don't understand why you always calculate the other columns from the total position and not row by row? 
The value for column 2 is again the value for the entire position.
Why is it not the current price * the number in this row times the multiplier?
The value in column 3 also seems to come from the total position. Please switch to line-by-line calculation here as well.
The profit in column 4 is also clearly wrong. It is somewhere between 21-26%. It depends on which price you take from the TWS for the calculation.

Translated with DeepL.com (free version)

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/2206af49-cf17-4989-be53-1d647eeaf05d)

**Comment by PaulSquires** [comment] 2024-01-08 17:27
I uploaded new code for the live data grid. I changed where some column data is displayed as well as use better data for the individual line calculations. I have not tested it a 100% yet but hopefully I will have time today to test.

**Comment by Flippo24** [comment] 2024-01-08 18:55
That's what I wanted to see. Thanks a lot.

However, I still have one problem. But this has nothing to do with your current change. Can you have a look at why no values are displayed for these items?

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/e427f4fa-5a45-46eb-bf13-6bc7b74940fd)

**Comment by Flippo24** [comment] 2024-01-08 20:26
The width of the fourth column could be slightly larger. Maybe an automatic adjustment of the width across all values of the column makes sense, in combination with a minimum width. 
What about a space between the value and the %? Does that make sense? Could be my eyes are not the best anymore. 
Do the brackets make sense at all or can you leave them out?

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/1adc836e-456e-47a1-8dea-ba339f101940)

**Comment by Flippo24** [comment] 2024-01-08 20:32
If the brackets only show that the position is in loss, then I would prefer a "-" in front of the value. I think the red color is right.

**Comment by PaulSquires** [comment] 2024-01-08 21:06
> The width of the fourth column could be slightly larger. Maybe an automatic adjustment of the width across all values of the column makes sense, in combination with a minimum width. What about a space between the value and the %? Does that make sense? Could be my eyes are not the best anymore. Do the brackets make sense at all or can you leave them out?
> 
> ![grafik](https://private-user-images.githubusercontent.com/5230426/295027131-1adc836e-456e-47a1-8dea-ba339f101940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NDgwOTYsIm5iZiI6MTcwNDc0Nzc5NiwicGF0aCI6Ii81MjMwNDI2LzI5NTAyNzEzMS0xYWRjODM2ZS00NTZlLTQ3YTEtOGRlYS1iYTMzOWYxMDE5NDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMjEwMzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJlZGY5NzkzNmM0OWQxMDRlNjIyMTA2YTA4MTI5NDcxZmY5NGE1NTc3ZjQ0NGYxOWMyNWE1ZTcyZDE5OWNiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RyORDAooB1efRxkEu0iFARZOE7V0jLP-WjPABCgxhEo)

Thanks, I will look at this tomorrow. There is code that should automatically resize the columns contents based on min/max widths. I will check to ensure that code is being applied to that fourth column. I should be able to change from "(  )" to negative signs.

I haven't had much time to day to test or code anything so hopefully tonight and tomorrow I can get things correct.

**Comment by Flippo24** [comment] 2024-01-08 21:13
I don't expect you to solve things for me immediately. I'm already quite happy with your work.

Speaking of work. I have something else for you...
When I pull data from Yahoo, it only shows the price of the underlying and that the position is ITM. But all other values are missing. No values for the legs and the total PnL.
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/c236fb0d-303e-42c2-b6ef-eb8f336f50c2)

**Comment by PaulSquires** [comment] 2024-01-09 02:34
Here is what it looks like with the minus sign and space before the %.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/cfb6fa68-7635-4cf9-82b4-517e49edc627)

Here is what it looks like with ZERO decimal places instead of TWO.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/d3fb47dc-3b93-4cdb-8825-61b4f3c4befa)


Do you have a preference???   (I just committed the source using MINUS sign, SPACE before %, and ZERO decimal places if you 
want to see it for yourself.

I have a few other areas in the program that use parenthesis instead of minus. I should just change everything to minus, right?

**Comment by Flippo24** [comment] 2024-01-09 12:28
My favorite would be the second one, without the decimal points and with the space. It looks cleaner.

Your TradeTracker is getting better every day!

**Comment by PaulSquires** [comment] 2024-01-09 13:26
> My favorite would be the second one, without the decimal points and with the space. It looks cleaner.

I think that I like that version also. 😀 

> Your TradeTracker is getting better every day!

Thanks! I am very happy with all of the suggestions you've provided to make this program better. It has come a long way in just a week or so.  👍

**Comment by Flippo24** [comment] 2024-01-09 13:44
You should have asked for my help earlier.  :laughing:

**Comment by Flippo24** [comment] 2024-01-09 14:01
Not so quick to close.
Please note these two comments from me, which have not yet been edited.

https://github.com/PaulSquires/TradeTracker/issues/16#issuecomment-1881649268
https://github.com/PaulSquires/TradeTracker/issues/16#issuecomment-1881831017

**Comment by PaulSquires** [comment] 2024-01-09 14:09
I swear I responded to the Yahoo data question! I must have typed it and not hit submit. For Yahoo data, I am only scrapping the price data because I expected that the Options data would be very hard to scrap. I think that I will convert this into a Discussion for a future enhancement.

**Comment by PaulSquires** [comment] 2024-01-09 14:10
I admit, I skipped or forgot about the other issue! Let me take a look at that one.

**Comment by Flippo24** [comment] 2024-01-09 14:24
But exactly this possibility gives people without Interactive Brokers the opportunity to use your program.

**Comment by PaulSquires** [comment] 2024-01-09 14:35
> That's what I wanted to see. Thanks a lot.
> 
> However, I still have one problem. But this has nothing to do with your current change. Can you have a look at why no values are displayed for these items?
> 
> ![grafik](https://private-user-images.githubusercontent.com/5230426/295008688-e427f4fa-5a45-46eb-bf13-6bc7b74940fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDkyODgsIm5iZiI6MTcwNDgwODk4OCwicGF0aCI6Ii81MjMwNDI2LzI5NTAwODY4OC1lNDI3ZjRmYS01YTQ1LTQ2ZWItYmYxMy02YmM3Yjc0OTQwZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMTQwMzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ1NmM4YmExZTI2ZDQ3ZjY0MDBiMzAxMmExNTcwN2Q0OTI3NjIzNDE0NmJlMGI2NzU1YWI4MGFmODc3ODQyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SQ69QauG_vhCDj0VL5zpAAWXAY0LBl-vTTXXJkBvV0c)

I have uploaded new source code that enables you passing the "-console"  (with the double quotes) command line switch to the TradeTracker.exe program and it will display incoming TWS ticker data. Try it and see if you are receiving any data for those tickers in your screenshot.

**Comment by Flippo24** [comment] 2024-01-09 17:51
What happens under the hood? Do you retrieve the portfolio from the TWS and then look for all the tickers in the portfolio? Or do you look for the ticker entered in the trade in your app?

**Comment by PaulSquires** [comment] 2024-01-09 18:18
There is really two processes that happen. The first is subscribing and receiving Ticker data (basically the real time price action); and second, is retrieving Portfolio data for each open position. I create a vector (resizable array) of all Trades that are open. I then loop that vector and send calls to TWS to initiate sending me the data.

There are callbacks in the TradeTracker code that receive the data from TWS. When the Ticker and Portfolio data is received I store (or update existing) that data in an unordered_map (basically an associative array). I have a background thread running every second that loops the active trades grid and updates any information that has changed based on the map data. This is when you will see the ticker prices change or option legs data update.

**Comment by Flippo24** [comment] 2024-01-09 18:26
Ok my background on the trade and why I want to know:
There was a stock split at TMF. The current option is now continued under the ticker TMF1. I also find the same option in the TMF options chain, with the adjusted strike price. So TMF Jan19 6 put became TMF Jan19 60 put. The original option is now called TMF1 Jan19 6 Put. Which I still have in my portfolio. I have entered the new name in the TradeTracker because otherwise the price of the underlying would not fit.

**Comment by Flippo24** [comment] 2024-01-09 18:35
Ok since it's the ticker from TradeTracker, I have to pass the ball to you. Please recreate the trade as in my picture and check why no data is being fetched for it. TMF1 is displayed in the console, although I have not entered it anywhere in TradeTracker.

**Comment by PaulSquires** [comment] 2024-01-09 18:56
That does help actually. What was your original Trade BEFORE the split and before you made any additional entries in TradeTracker. If I know what your original starting point was then maybe I can offer suggestion on how the subsequent split should have been entered.

It was probably this, right?

TMF
-20 PUT 2024-01-19 @ $6
-40 PUT 2024-02-16 @ $6

**Comment by PaulSquires** [comment] 2024-01-09 18:58
When I look at "TMF1" on TWS it displays "Basket". I'll have research what that means and how it affects the data.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/72084de7-647b-4015-83e0-37e994c696b2)

**Comment by Flippo24** [comment] 2024-01-09 19:04
As you can see, they are available in the right ticker.
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/8a0a512f-eea3-4f75-a6f3-f1d868fd674c)

**Comment by PaulSquires** [comment] 2024-01-09 19:07
I have to go out for an hour! Damn. 
I will dig deeper into your posts as soon as I get back. Hang in there, we'll figure it all out.

**Comment by Flippo24** [comment] 2024-01-09 19:40
Lol. You seem to be there with heart and soul.

**Comment by PaulSquires** [comment] 2024-01-09 21:09
I don't know why IBKR is not correcting the TMF1 -20 PUT 2024-01-19 $6  ---> TMF -2 PUT 2024-01-29 $60 when it sends you the data. Likewise the -40 TMF1 and -2 TMF 2024-02-16 $60 are not being combined. Granted, they are separate symbols in IBKR's eyes (TMF1 and TMF).

I wish I could explain why IBKR handles the data the way that they do for this scenario.

I wonder if you enter the Trades as follows would they then receive the TWS data:

TMF1 -40 PUT 2024-02-16 @ $6
TMF1 -20 PUT 2024-01-19 @ $6

TMF -2 PUT 2024-02-16 @ $60

I have done some online searches to see if this kind of situation has been explained but I have not found anything relevant.

**Comment by Flippo24** [comment] 2024-01-09 22:51
That doesn't work either.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/c7859af1-c511-4fbf-b0bb-a421bd122c5f)

I once entered a TSLA position which I do not have. I don't get any data there either.
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/317f4f89-e1c9-4bc1-b759-9b72128632a4)

The TSLA positon is not displayed in the console. It looks as if only the tickers from the IB portfolio appear in the console, not those from TradeTracker.

**Comment by Flippo24** [comment] 2024-01-09 22:54
Could it be that you only subscribe to the tickers that are in the IB portfolio and not those from TradeTracker?

**Comment by PaulSquires** [comment] 2024-01-09 23:30
TradeTracker can get the **Ticker data** for whatever symbol that you set up for in the Trade. 

However, TradeTracker will only get the **portfolio/leg/option data** for positions that you actually own in IB. This is because your entire Portfolio in IB sent to TradeTracker when the program starts and TradeTracker matches the incoming ContractID's fro the TWS data to Trades that you have set up manually locally. Once the match has been made then TradeTracker knows which Contract ID's to capture whenever subsequent TWS related to your open positions arrives.

This is part of the matching code logic that TradeTracker uses internally to match IBKR data to your local Trade data:
```
// ========================================================================================
// Test if IBKR and LOCAL position are equal
// ========================================================================================
bool Reconcile_ArePositionsEqual(positionStruct ibkr, positionStruct local) {
	if (ibkr.underlying == L"OPT" ||
		ibkr.underlying == L"FOP") {
		if (ibkr.strike_price == local.strike_price &&
			ibkr.open_quantity == local.open_quantity &&
			ibkr.ticker_symbol == local.ticker_symbol &&
			ibkr.expiry_date == local.expiry_date &&
			ibkr.put_call == local.put_call &&
			ibkr.underlying == local.underlying) {
			return true;
		}
	}
	if (ibkr.underlying == L"STK" ||
		ibkr.underlying == L"FUT") {
		if (ibkr.open_quantity == local.open_quantity &&
			ibkr.ticker_symbol == local.ticker_symbol &&
			ibkr.underlying == local.underlying) {
			return true;
		}
	}

	return false;
}
```

**Comment by PaulSquires** [comment] 2024-01-09 23:37
> That doesn't work either.
> 
> ![grafik](https://private-user-images.githubusercontent.com/5230426/295361470-c7859af1-c511-4fbf-b0bb-a421bd122c5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NDI5MTQsIm5iZiI6MTcwNDg0MjYxNCwicGF0aCI6Ii81MjMwNDI2LzI5NTM2MTQ3MC1jNzg1OWFmMS1jNTExLTRmYmYtYjBiYi1hNDIxYmQxMjJjNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMjMyMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU3YzVkODA5NzViMzFkMWMwNzc0MWJmZDhlMWJmMDI2ZmMxOTExZjZiNGEzYWMyYTg1YWVlOWU2ODI5ZThhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Xh3J2tzEDcKGxxKX5wiHHnlnOO2eXSo8BeQucHE2Ads)

I am thinking that "TMF1" is a ticker that will no longer generate data because it is superseded by the data in "TMF". I honestly do not know for sure. This whole stock split and how IBKR deals with the handling of data related to pre and post split is all new to me.

**Comment by Flippo24** [comment] 2024-01-09 23:39
> However, TradeTracker will only get the portfolio/leg/option data for positions that you actually own in IB.

This must be changed. 
In the current case, IB is the master with its portfolio as the database.
I think it is better if TradeTracker is the master.
Query the ContractID for all positions in TradeTracker and then subscribe to the data. No matter what is in the portfolio.

**Comment by PaulSquires** [comment] 2024-01-09 23:57
I understand what you mean and I am pretty sure that I can query IB for contracts based on stock, option, futures, attributes. I would just have to test to see what streaming data gets received by TradeTracker for all of those different types of underlyings. Actually, since we changed the way we calculate the position cost and display it ActiveTrades grid, the data that we really need on a real time basis from IB would be the current market price.

I could then continue to use the Reconcile function to retrieve IB based Portfolio data and compare to local data to ensure that you have not entered local data incorrectly causing a mismatch to what positions you actually own.

I guess my only question is: Why would you want to set up a Trade locally within TradeTracker that you do not actually own based on the data in IB???? I am trying to think of a scenario where that would be useful?

I am certainly open to changing the way TradeTracker requests information but I would have to do some testing first to make sure that we are not losing any functionality that we currently have.

**Comment by PaulSquires** [comment] 2024-01-10 02:34
I have tried your new approach but (so far) I am unable to retrieve option data for stocks or futures. It could be because the market is closed but I will try again tomorrow during regular trading hours. (I am using the reqMktData api).

**Comment by Flippo24** [comment] 2024-01-11 10:07
I'm wondering a few things here. 

Why are the two values marked in green the same if they are different strike prices? I saw this in your pictures and not just for one trade. 

The 756.82 marked in red should be negative. Since you get money when you sell the position. If it goes according to the money flow. 
I don't understand the calculation of the profit. You paid 2450.71$ for this put. This is still worth 756.82$. Then the profit should be -1693.89$ and -69.11%.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/743b19bd-6ed6-4b1b-9b72-d08080a5aa84)

**Comment by Flippo24** [comment] 2024-01-11 11:18
I find the way you use the income and expenditure with the signs very difficult to interpret. It may be that the way you do it is right, but I would always do it from the point of view of my account.
When I sell something, I get money for it. Positive.
If I sell a put, I get a positive premium. If I have to buy it back, that would be negative because I have to spend money.
The statistics under Closed Trade are also positive for profits and not negative. Think about it.

**Comment by PaulSquires** [comment] 2024-01-11 11:22
Good morning, the first column is always the money you have received for the position. The second column is the current market value of the position if you sold it right now. The 3rd and 4th columns are the difference and percentage.

It looks like that screenshot you posted is from 3 days ago and there have been fixes to the calculations since then. Here is what that exact same position looks like now:

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/94a31871-1dc5-4459-9762-7b17f7e2683c)

The first column is calculated by assigning the total amount of cash received for the trade ($756.82) among the 3 different legs based on their percentage of contracts. That may not be the best way to do it but I am not sure what the alternative would be? I agree that I should not be playing with the negatives and I will fix that.

Here is what the costs of that Trade is showing right now:

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/f44f5106-4b0c-4254-b39d-311a43cecc67)


And here is the market value of the Trade:

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/597e270f-c660-4ac5-a784-c43370172ed6)

It has been the calculation and display of the individual leg positions that has caused us problems over the past week. I wonder if it would be an idea to receive the TWS reported costs of the 3 legs, total them, and then use each of their proportions to multiply against the amount received. That might be okay? Using that approach I would not have had to gone the path of tracking individual leg costs from transaction to transaction.

I think more thinking and head scratching might be needed here.  😁

**Comment by Flippo24** [comment] 2024-01-11 11:40
I'm really sorry if I keep coming back to the point. But actually I expect exactly the same values in the TradeTracker as in the TWS. The profit of 611% is simply misleading. 

What would be wrong with changing the order management window so that you enter the buy price for each leg instead of a total price? That would be the most accurate. All values can be seen in the TWS after the order has been executed.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/52d7ec2f-56ec-4ef0-aa65-b712b790be99)

**Comment by Flippo24** [comment] 2024-01-11 11:43
Another total field for price and fee below the input fields. But only as a display.

**Comment by PaulSquires** [comment] 2024-01-11 12:53
I like your ability to photoshop a new screen layout design 👍

**Comment by PaulSquires** [comment] 2024-01-11 12:55
How about something like this. This would make it a lot easier when calculating the cost basis based on incoming TWS data:

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/7d767efc-e176-459d-aed1-f1e6ae7388db)

**Comment by Flippo24** [comment] 2024-01-11 13:00
I don't know what sense a ratio should make at this point. If a leg costs a certain price, then it costs exactly that price and not an adjusted one via a ratio.

**Comment by Flippo24** [comment] 2024-01-11 13:16
Why isn't it easier this way?
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/f7409f9e-ca4f-4d46-bd24-841905341409)
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/e3511788-a166-4b6b-b29b-898116e48ef1)

**Comment by PaulSquires** [comment] 2024-01-11 14:12
![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/799a11ae-1045-4e62-8f4a-6f5811d27f49)

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/a5f78228-da72-4e3a-8aa0-5ab352f37e6b)

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/8d9c9b7d-2493-4513-927f-55747f6b99c3)


In the previous exampe there were no Rolls. This example, using a simple /ES Strangle has several rolls and as you can see, how do we equate the TWS reported cost values (-7869) to the ongoing profit/loss that we have manually recorded (3007.96? That's why I thought that using a ratio would work.

**Comment by Flippo24** [comment] 2024-01-11 14:44
I find this very difficult and complicated.
I don't know exactly how much you paid for rolling to buy back your positions. 

I think the cost basis is 7869 - 3007.96. 
But again, you can always look at both legs separately, as both legs were rolled individually. Which again means that you don't need a ratio.
Take the transactions and look at the whole thing as if the rolling is the closing of the trade and afterwards you open a new trade. What kind of position do you end up with? I think the one shown in the TWS. In the end it's a philosophy question, is the roll part of the trade or are there two trades.

**Comment by PaulSquires** [comment] 2024-01-11 15:13
> I find this very difficult and complicated. 

I do also.  😁 

> I think the cost basis is 7869 - 3007.96. 

I would think that the cost basis would be 3007.96 because that is how much money we received by selling the Puts and subsequent incremental income from rolling. When I am evaluating my position, I want to see how much the position is worth at the current market value, versus how much income I have currently collected. It is the allocation of the costs to the legs that is problematic.

> In the end it's a philosophy question, is the roll part of the trade or are there two trades.

I agree that it is two trades and IB treats them that way (as do all brokers) because when you roll you'll see the realized gain/loss immediately. Of course the problem is that users want to treat all the rolls as part of a single trade.

I think I need more thinking.... maybe I will work on something else and let this sit in my subconscious for a while and wait for that "Eureka Moment" to hit me.  😀

**Comment by PaulSquires** [comment] 2024-01-11 16:05
Okay, I've done more thinking about this. The fundamental problem is getting an accurate starting cost for the legs. Once we have that value then all subsequent transactions involving adding or reducing costing to the legs is easy, and that code is already part of TradeTracker.

A few days ago, to calculate that starting point, I included programming logic to simply use the ratio of contracts of the leg to the total contracts of the transaction and multiply that by the income received for the entire transaction. Of course, that is not accurate as some of the long and short legs and put/call skew would value the legs differently.

An option would be that when the initial transaction is created, set the legs cost basis to zero, and respond to the first incoming TWS message for that Trade. That message would have the true initial costs of the legs. I would simply test to see that the leg's cost is currently zero and if it is, then assign the incoming TWS cost data.

The problem with the above is that it assumes that the user has only entered that first transaction and no other in the same trade. If the user is NOT connected to TWS and enters several transactions for the trade and then later connects to TWS, then I would never get that initial cost data (I would only get the data for most recent transaction). This is the same problem that we are facing right now.  I have trades with many transactions and no way to get the initial starting cost.

I do not want to go down the path of making the user try to find this cost data for themselves. Maybe there is a IB report that can be run that shows the evolution of the costs but once I force users to have to generate reports just to enter data, then I bet 99% of them will give up and abandon TradeTracker because it will become a hassle. The whole idea of this program from the very beginning was to make things easy. :grin:

So, once again, I come back to the ratio approach...... or, should I say, "relative cost base" of the leg. Every time I receive a TWS data message about the Trade, I can calculate the relative costing of the all the legs compared to the overall income received to date for the Trade. 

Is it perfect? Maybe not. 

Is it close to what the actual costs would be? Maybe.

Another benefit of using this relative cost base approach is that it is easy to implement and willl easily work with existing data and the data of previous TradeTracker (IB-Tracker) databases. Previous users would simply need to start using TradeTracker and everything would work seamlessly under the hood.

Anyway, I will continue to do more thinking.....

**Comment by Flippo24** [comment] 2024-01-11 16:21
I can't quite share your approach of extracting as much data as possible from the TWS and doing "too much" work for the user. As long as everything works, it's ok. But if other numbers appear and the user does not understand transparently where they come from or what is behind them, it becomes difficult. Maybe I'm the wrong person to ask and it would be interesting to hear other opinions.

**Comment by PaulSquires** [comment] 2024-01-18 15:49
> I have introduced a GPF when closing a Trade when Live Data connected to TWS. I hope to have this fixed ASAP.

Okay, should be fixed now.

**Comment by PaulSquires** [comment] 2024-01-25 16:05
Finally, I have have the live Option Leg portfolio data matching the streaming data from TWS. Turned out it was a simple and straight forward implementation. Too bad I wasted so much time on this issue running around in circles. Code is now in the repository and an updated testing EXE posted to https://github.com/PaulSquires/TradeTracker/releases

**Closed** 2024-01-25 17:45 UTC
Labels: enhancement
